# Generated by Django 5.2.7 on 2025-10-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(help_text='Separe as tags por vírgula. Ex: React,Node.js,PostgreSQL', max_length=255)),
                ('link_github', models.URLField()),
                ('link_demo', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
